### ISSUE TITLE
Hello, some doubts about the results of the autoeval

### ISSUE THREAD

**Issue by cyzLoveDream** [tuhinjubcse/SimileGeneration-EMNLP2020#3]
Thank you very much for this repo. I also run this repo. I have some questions and would like to ask.
The main problems are as follows:
1. When I run autoeval.py according to the code in the repo, I got a different result from the paper, and the difference is big. As shown in the figure, 
![d](https://user-images.githubusercontent.com/23023057/96072999-169c5100-0ed8-11eb-8ddc-83c7b6dbd459.PNG)
I modified the code in this line under the autoeval.py file. Otherwise, I will report such an error. 
![d2](https://user-images.githubusercontent.com/23023057/96073028-24ea6d00-0ed8-11eb-94a1-3591ea5ce8f9.png)
When I modified the code, I got extremely low results. just like the figure.
Want to ask what went wrong?
2. When I used autoeval.py to verify BERTsocre, I got this error, and I want to ask how to solve it.
![d3](https://user-images.githubusercontent.com/23023057/96074528-7f38fd00-0edb-11eb-9f96-ae9a89a2fb99.png)
After I fixed this bug, I still got poor results.
![d4](https://user-images.githubusercontent.com/23023057/96074776-0a19f780-0edc-11eb-9caa-f3aa803fa939.PNG)

**Comment by tuhinjubcse** [comment]
Its the same as paper you should multiply it by 100 that's the protocol 
0.0803*100 == 8.03
0.03599*100 = 3.599

**Comment by tuhinjubcse** [comment]
I will look in the BERT score bit in a few days . Thanks .

**Comment by cyzLoveDream** [comment]
> Its the same as paper you should multiply it by 100 that's the protocol
> 0.0803_100 == 8.03 0.03599_100 = 3.599

Thanks, Regarding the BERTscore calculation, if you put it in the "for" loop, each calculation will reload the Roberta-large pre-trained model. Over time will lead to OOM, it is recommended to put it outside for calculation

**Comment by tuhinjubcse** [comment]
It worked for me use GPU
